---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: api-henrique
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: 132818155912.dkr.ecr.us-east-1.amazonaws.com/api_henrique
  interval: 1m0s
